### ISSUE TITLE
Integration Error to GIO

### ISSUE THREAD

**Issue by sureshhewabi** [bezzlab/mzIdentMLVisualiser#7]
-----Original Message-----
From: gioatqmul@gmail.com [mailto:gioatqmul@gmail.com] 
Sent: 15 July, 2016 3:01 AM
To: Jun Fan j.fan@qmul.ac.uk; Jun Fan j.fan@qmul.ac.uk
Subject: Galaxy tool error report from j.fan@qmul.ac.uk (mzIdentMLToJSON)
## This is in reference to dataset id 13782 (6fe1b2553ec2b8e3) from history id 12201 (842e3a8e9b827812)

You should be able to view the history containing the related history item (fc4ce51c339d6712)

11: mzIdentMLToJSON on data 10

by logging in as a Galaxy admin user to the Galaxy instance referenced above and pointing your browser to the following link.
## http://gio.sbcs.qmul.ac.uk/history?id=842e3a8e9b827812

The user 'j.fan@qmul.ac.uk' provided the following information:

---

info url: http://gio.sbcs.qmul.ac.uk/datasets/fc4ce51c339d6712/show_params
job id: 12791 (e933bff4f37b8757)
tool id: mzIdentMLToJSON
tool version: 1.0.0
job pid or drm id: 20714
## job tool version: 

job command line:
## python /home/galaxy/galaxy/../gio_applications/misc/mzIdentMLToJSON.py  --filename="/home/galaxy/galaxy/database/files/013/dataset_13781.dat" --datasetid=f6e329f1fcc0c7ee

job stderr:
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/qmul/pv/control/ProViewer : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

---

job stdout:
/home/galaxy/galaxy/database/job_working_directory/012/12791

---

job info:
## None

job traceback:
## None

(This is an automated message).

**Comment by sureshhewabi** [comment]
this was a versioning issue. GIO had JDK 7 while code is compiled in JDK 8. This was fixed by installing JDK 8 to the GIO cent OS.
